apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.0
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  POSTGRES_PASSWORD: "UGcjMTIz"
  POSTGRES_USER: "a3ViZWRldm5ld3M="
  POSTGRES_DB: "a3ViZWRldm5ld3M="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubedevnews"
spec:
  selector:
    matchLabels:
      app: "kubedevnews"
  template:
    metadata:
      labels:
        app: "kubedevnews"
    spec:
      containers:
      - name: "kubedevnews"
        image: jvictorsm/news:1.0.0
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: news
---
apiVersion: v1
kind: Secret
metadata:
  name: news
type: Opaque
data:
  DB_HOST: "cG9zdGdyZXNxbA=="
  DB_DATABASE: "a3ViZWRldm5ld3M="
  DB_USERNAME: "a3ViZWRldm5ld3M="
  DB_PASSWORD: "UGcjMTIz"
---
apiVersion: v1
kind: Service
metadata:
  name: "kubedevnews"
spec:
  selector:
    app: "kubedevnews"
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort

